version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 16 * * 5"
      timezone: "Asia/Shanghai"
    reviewers:
      - "yusancky"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 16 * * 5"
      timezone: "Asia/Shanghai"
    reviewers:
      - "yusancky"
    labels:
      - "dependencies"
