version: '1.0'

name: push
displayName: Push

triggers:
  trigger: auto
  push:
    branches:
      precise:
        - artifact/refs/heads/main

stages:
  - name: push
    displayName: push
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: push
        displayName: push
        pythonVersion: '3.12'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip install -r requirements.txt
          - python3 ./push.py
        caches: []
        notify: []
        strategy:
          retry: '0'
          timeout: 3
