name: activities-bugfix-2025
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/.common.yml'
      - '.github/workflows/activities-bugfix-2025.yml'
      - 'activities/bugfix-2025/**'
      - 'AllUp_utils/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - '.github/workflows/.common.yml'
      - '.github/workflows/activities-bugfix-2025.yml'
      - 'activities/bugfix-2025/**'
      - 'AllUp_utils/**'
      - 'requirements.txt'
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 3,7,11,15 * 6,7,8 *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  activities-bugfix-2025:
    uses: ./.github/workflows/.common.yml
    with:
      script: activities/bugfix-2025/main.py
