name: activities-bugfix
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/.common.yml'
      - '.github/workflows/activities-bugfix.yml'
      - 'activities/bugfix.py'
      - 'AllUp_utils/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - '.github/workflows/.common.yml'
      - '.github/workflows/activities-bugfix.yml'
      - 'activities/bugfix.py'
      - 'AllUp_utils/**'
      - 'requirements.txt'
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  activities-bugfix:
    uses: ./.github/workflows/.common.yml
    with:
      requirements: activities/bugfix-requirements.txt
      script: activities/bugfix.py
    secrets: inherit
