name: activities-bugfix-2025
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/.common.yml'
      - '.github/workflows/activities-bugfix-2025.yml'
      - 'activities/bugfix-2025.py'
      - 'AllUp_utils/**'
      - 'requirements.txt'
  pull_request:
    paths:
      - '.github/workflows/.common.yml'
      - '.github/workflows/activities-bugfix-2025.yml'
      - 'activities/bugfix-2025.py'
      - 'AllUp_utils/**'
      - 'requirements.txt'
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 0,6,8,9,12,13,15,16 * 7,8 *'
    - cron: '0 16 * 9 *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  activities-bugfix-2025:
    uses: ./.github/workflows/.common.yml
    with:
      script: activities/bugfix-2025.py
    secrets: inherit
